### ISSUE TITLE
I do not know why the _post page is creating subfolders with year-day-month/title.html . 

### ISSUE THREAD

**Issue by imvieira** [pietromenna/jekyll-architect-theme#16]
I have followed the step-by-step about blogging from the link https://jekyllrb.com/docs/step-by-step/08-blogging/

The file _posts/ 2018-08-20-bananas.md has been created.

However, when I access the site https://imvieira.github.io/wiki/blog.html, the post *Apples* is linked to the URL: https://imvieira.github.io/2018/08/21/apples.html

But I do not know why the page is creating subfolders with year-day-month/title.html .

**Comment by pietromenna** [comment]
Hi @imvieira . Where can I look at the settings you are using? Are you using a fork of this repository or you are using directly the there from GitHub pages?
